//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonPortable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public Relation()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int RelationId { get; set; }
        public int FirstUserId { get; set; }
        public int SecondUserId { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
        public virtual Usr Usr { get; set; }
        public virtual Usr Usr1 { get; set; }
    }
}
