//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonPortable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public System.Guid RequestId { get; set; }
        public int RelationId { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<bool> Finished { get; set; }
        public Nullable<double> LatFirstUser { get; set; }
        public Nullable<double> LngFirstUser { get; set; }
        public Nullable<double> LatSecondUser { get; set; }
        public Nullable<double> LngSecondUser { get; set; }
    
        public virtual Relation Relation { get; set; }
    }
}
