//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usr
    {
        public Usr()
        {
            this.Relations = new HashSet<Relation>();
            this.Relations1 = new HashSet<Relation>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> Verified { get; set; }
    
        public virtual ICollection<Relation> Relations { get; set; }
        public virtual ICollection<Relation> Relations1 { get; set; }
    }
}
